Repository ELIXIR-NO/FEGA-Norway, pull requests merged in 2023-12, with the labels that each got.

#3 Workflows/auto formatting
  build.gradle.kts
Labels: Root, configuration

#5 Add Spotless formatting conventions setup
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/formatting-conventions.gradle.kts
Labels: Root, configuration

#6 Add GitHub Actions workflows for build, test and check formatting
  .github/workflows/build-and-test.yml
  .github/workflows/check-formatting.yml
Labels: workflows

#4 Import clearinghouse
  lib/clearinghouse/build.gradle.kts
  lib/clearinghouse/src/main/java/no/uio/ifi/clearinghouse/Clearinghouse.java
  lib/clearinghouse/src/main/java/no/uio/ifi/clearinghouse/JWKProvider.java
  lib/clearinghouse/src/main/java/no/uio/ifi/clearinghouse/model/ByValue.java
  lib/clearinghouse/src/main/java/no/uio/ifi/clearinghouse/model/Visa.java
  lib/clearinghouse/src/main/java/no/uio/ifi/clearinghouse/model/VisaType.java
  lib/clearinghouse/src/test/java/no/uio/ifi/clearinghouse/ClearinghouseTests.java
  lib/clearinghouse/src/test/java/no/uio/ifi/clearinghouse/CredentialsProvider.java
  lib/clearinghouse/src/test/resources/access-token.jwt
  lib/clearinghouse/src/test/resources/jwk.json
  lib/clearinghouse/src/test/resources/oidcConfig.json
  lib/clearinghouse/src/test/resources/passport.json
  lib/clearinghouse/src/test/resources/private.pem
  lib/clearinghouse/src/test/resources/public.pem
  lib/clearinghouse/src/test/resources/visa.jwt
  settings.gradle.kts
Labels: Clearinghouse, import

#18 Add new plugins and build conventions for SpringBoot applications
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/springboot-conventions.gradle.kts
Labels: Root
